name: My GHA
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: fmi-basel/gliberal-scMultipleX.git

      - name: Run a one-line script
        run: git clone https://github.com/

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
