name: My GHA
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: fmi-basel/gliberal-scMultipleX

      - name: Run a one-line script
        run: ls

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
