name: My GHA
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
