name: My GHA
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-22.04
    steps:

      # Get Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      # Get package source code
      - uses: actions/checkout@v4
        with:
          repository: fmi-basel/gliberal-scMultipleX
          
      # Install package
      - name: Install package
        run: python -m pip install -e .[fractal-tasks]

      # Create manifest
      - name: Create manifest
        run: python src/scmultiplex/dev/create_manifest.py

      # Run git diff for manifest
      - name: Manifest diff
        run: git diff src/scmultiplex/__FRACTAL_MANIFEST__.json

      - name: Report dirty status
        run: |
          [[ -n $(git status -s) ]] && echo 'Status is dirty, exit 1.' && exit 1

      - name: Report clean status
        run: |
          [[ -z $(git status -s) ]] && echo 'Status is clean, exit 0.' && exit 0

