name: My GHA
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  test1:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        external_github_repository: [skip]
        cmd_install: [skip]
        include:
          - external_github_repository: fmi-basel/gliberal-scMultipleX
            cmd_install: 'python -m pip install -e .[fractal-tasks]'
        exclude:
          - external_github_repository: skip
            cmd_install: skip
    steps:

      - name: Print info
        run: |
          echo 'repo: ${{ matrix.external_github_repository }}' |
          echo 'cmd_install: ${{ matrix.cmd_install }}' |
          

      # Get package source code
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.external_github_repository }}

      # Get Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      # Install package
      - name: Install package
        run:  ${{ matrix.cmd_install }}

      # Create manifest
      - name: Create manifest
        run: python src/scmultiplex/dev/create_manifest.py

      # Run git diff for manifest
      - name: Manifest diff
        run: git diff src/scmultiplex/__FRACTAL_MANIFEST__.json
        
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
        
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo 'Changes exist' && exit 1
