name: My GHA
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


# Example of paramtrization, based on https://stackoverflow.com/a/68940067/19085332

# steps:
#   - name: Compile with C++ compiler
#     run: ${{ matrix.case.repository }} ..
#   - name: Compile with C compiler
#     run: ${{ matrix.compiler.c }} source.c
  

jobs:
  test1:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        external_github_repository: [skip]
        version: [skip]
        include:
          - external_github_repository: fmi-basel/gliberal-scMultipleX
            version: myversion
        exclude:
          - external_github_repository: skip
            version: skip
    steps:

      - name: Print info
        run: |
          echo 'repo: ${{ matrix.external_github_repository }}'

      # Get package source code
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.external_github_repository }}

      # Get Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      # Install package
      - name: Install package
        run: python -m pip install -e .[fractal-tasks]

      # Create manifest
      - name: Create manifest
        run: python src/scmultiplex/dev/create_manifest.py

      # Run git diff for manifest
      - name: Manifest diff
        run: git diff src/scmultiplex/__FRACTAL_MANIFEST__.json
        
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
        
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo 'Changes exist' && exit 1
